# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               gdelazzari
tagline:             "another student's blog"
description:         "Blog of an italian IT student. Software, electronics, microcontrollers, robotics and stuff."
url:                 "http://gdelazzari.github.io/"
baseurl:             ""
paginate:            5

# About/contact
author:
  name:              Giacomo De Lazzari
  url:               http://gdelazzari.github.io/
  email:             giacky98.mail@gmail.com
  github:            gdelazzari

# Gems
gems: [jekyll-paginate]

# Exclusions
exclude: ['README.md']
